version: "3.8"

services:
  php-app:
    build: .
    container_name: php-app
    ports:
      - "8081:80" # Access your API here
    volumes:
      - .:/var/www/html
    restart: always
    # depends_on:
    #   - db

  # db:
  #   image: mysql:8
  #   container_name: mysql-db
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: pcrypt
  #     MYSQL_USER: docker
  #     MYSQL_PASSWORD: docker
  #   volumes:
  #     - db_data:/var/lib/mysql

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   restart: always
  #   ports:
  #     - "8082:80" # Open UI at http://localhost:8082
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORD: root
  #   depends_on:
  #     - db
# volumes:
#   db_data:
